---

- hosts: orarac
  vars:
    - oracle_linux_password: new123
    - oracle_grid_software_url: "/run/media/pierre/b651edce-0f5c-493e-8d05-2f10391f6b68/LINUX.X64_193000_grid_home.zip"
    - oracle_db_software_url: "/run/media/pierre/b651edce-0f5c-493e-8d05-2f10391f6b68/LINUX.X64_193000_db_home.zip"

  remote_user: ansible
  become: yes
  become_method: sudo

  pre_tasks:

  - name: include variables
    include_vars: 
      file: develvar.yml

  - name: check that cluster scan resolves to 3 ip addresses
    command: "nslookup {{clustername}}-scan.{{domain}}"
    register: nslookup_scan

  - debug:
      var: nslookup_scan
  - name: cluster scan resolution
    assert:
      that: "{{ nslookup_scan.stdout_lines | select('match','^Name:') | list | length }} == 3"


  - meta: end_play

  -  debug:
       var: oracle.install.asm
  roles:
    - devel-grid
#    - oracle-grid
