---

- hosts: orarac
  vars:
    - oracle_linux_password: new123

  remote_user: ansible
  become: yes
  become_method: sudo

  pre_tasks:

  - name: include variables
    include_vars: 
      file: grid19var.yml

  - name: check
    include_tasks: check_cluster.yml

  - debug:
      var: check_crs_ok

  roles:
#    - {name: oracle-grid, when: check_crs_ok == False}
#    - {name: grid19, when: check_crs_ok == False}
#    - grid19-ru
#    - orarac19
    - orarac19-ru
