---

- hosts: phoenix
  vars:
    become: yes
    become_user: root
    become_method: sudo


  pre_tasks:
    - name: include_vars
      include_vars:
        file: "{{ stage_dir }}/content.yml"
        name: images
         
    - debug: var=images

  roles:
    - base
    - docker-ce
    - postgres
    - cluster
    - consul
    - docker_infra


...
