---
- hosts: phoenix
  vars:
  remote_user: vagrant
  become: yes
  become_method: sudo


  pre_tasks:
    - name: include_vars
      include_vars:
        file: art.yml
        name: images
         

    - debug: var=images


  roles:
    - base
    - docker-ce
    - postgres
    - cluster
    - consul
    - docker_infra
    
