---

  - name: add repository
    yum_repository:
      name: docker-ce-stable
      description: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
      gpgkey: https://download.docker.com/linux/centos/gpg
      state: present

  - name: add repository
    yum_repository:
      name: docker-ce-edge
      description: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/centos/7/$basearch/edge
      gpgkey: https://download.docker.com/linux/centos/gpg
      enabled: yes
      state: present

  - name: install docker-ce
    yum:
      name: docker-ce
      state: latest

  - set_fact:
      docker_pv: "{{ storage['docker'].disk }}"

  - name: create docker volume group
    lvg: 
      vg: "{{storage['docker'].vg}}"
      pvs: "/dev/{{ storage['docker'].disk }}"
      state: present
    when: >
     (hostvars[inventory_hostname]['ansible_lvm']['vgs'] is defined 
     and hostvars[inventory_hostname]['ansible_lvm']['vgs']['{{storage['docker'].vg}}'] is not defined)

  - name : create thinpool for docker
    lvol: 
      vg: "{{storage['docker'].vg}}"
      lv: thinpool
      size: "{{ ((storage['docker'].size_gb|int) * 0.9 * 1024) | int }}"
      opts: --wipesignatures y
      state: present
    when: hostvars[inventory_hostname]['ansible_lvm']['lvs']['thinpool'] is not defined

  - name : create meta for docker
    lvol: 
      vg: "{{ storage['docker'].vg }}"
      lv: thinpoolmeta
      size: "{{ ((storage['docker'].size_gb|int) * 0.1 * 1024) | int }}"
      opts: --wipesignatures y
    when:  hostvars[inventory_hostname]['ansible_lvm']['lvs']['thinpool'] is not defined
      
  - name: test if pool is already converted to thinpool
    shell: "lvs -o lv_attr {{ storage['docker'].vg }}/thinpool | tail -1 | awk '{print $1}' | cut -c1"
    register: thinpool_converted

  - debug: var=thinpool_converted
      
  - name: convert pool to a thinpool
    command: lvconvert -y --zero n -c 512K --thinpool {{ storage['docker'].vg}}/thinpool --poolmetadata {{ storage['docker'].vg }}/thinpoolmeta
    when: thinpool_converted.stdout != "t"

  - name: Configure autoextension of thin pools via an lvm profile
    copy:
      src: docker-thinpool.profile
      dest: /etc/lvm/profile/docker-thinpool.profile

  - name: Apply your new lvm profile
    command: lvchange --metadataprofile docker-thinpool {{ storage['docker'].vg }}/thinpool

  - name: create directory /etc/docker
    file: path=/etc/docker state=directory

  - name: configure docker daemon
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json

  - name: add group docker to evs
    user:
      name: pgadmin
      groups: "docker"
      append: yes

  - name: restart firewalld
    systemd:
      name: firewalld
      enabled: true
      state: restarted

  - name: start and enable docker
    systemd:
      name: docker
      enabled: true
      state: started
