---

#- name: change grub options
#  command: 'grubby --remove-args="rhgb quiet" --args="numa=off transparent_huge_page=never" --default-kernel=ALL'

- name: pre check
  include_tasks: precheck.yml

- name: create {{ grid_software_base }} directory
  file:
    path: "{{ grid_software_base }}"
    state: directory
    owner: "{{ grid_osuser }}"
    group: "{{ orainventory.osgroup }}"
    mode: 0750

- name: create {{ orainventory.location  }} directory
  file:
    path: "{{ orainventory.location }}"
    state: directory
    owner: "{{ grid_osuser }}"
    group: "{{ orainventory.osgroup }}"
    mode: 0775

- name: create {{ grid_oracle_base }} directory
  file:
    path: "{{ grid_oracle_base }}"
    state: directory
    owner: "{{ grid_osuser }}"
    group: "{{ orainventory.osgroup }}"
    mode: 0750

- name: create scripts directory
  file:
    path: "{{ grid_oracle_base }}/scripts"
    state: directory
    owner: "{{ grid_osuser }}"
    group: "{{ orainventory.osgroup }}"
    mode: 0775

- name: create admin directories
  file:
    path: "{{ grid_oracle_base }}/scripts/{{ item }}"
    state: directory
    owner: "{{ grid_osuser }}"
    group: "{{ orainventory.osgroup }}"
    mode: 0775
  with_items:
     - install 
     - sql
     - log
     - trace
     - GRID
     - audit

- name: create staging directory for grid
  file:
    path: "{{ grid_stage_location }}"
    state: directory
    owner: "{{ grid_osuser }}"
    group: "{{ orainventory.osgroup }}"
    mode: 0775

- name: create grid home
  file:
    path: "{{ grid_oracle_home }}"
    state: directory
    owner: "{{ grid_osuser }}"
    group: "{{ orainventory.osgroup }}"
    mode: 0775

- name: install grid installation zip file
  unarchive:
    src: "{{ oracle_grid_software_download_url }}"
    dest: "{{ grid_oracle_home }}"
    owner: "{{ grid_osuser }}"
    group: "{{ orainventory.osgroup }}"
  when: "inventory_hostname == groups.all[0]"

- name: fetch cvuqdisk rpm 
  fetch:
     src: "{{ grid_oracle_home }}/cv/rpm/cvuqdisk-1.0.10-1.rpm"
     dest: ./cvuqdisk-1.0.10-1.rpm
     flat: true
  when: "inventory_hostname == groups.all[0]"
  
- name: copy cvuqdisk rpm
  copy:
    src: ./cvuqdisk-1.0.10-1.rpm
    dest: /tmp

- name: install cvuqdisk rpm
  yum:
    name: /tmp/cvuqdisk-1.0.10-1.rpm
    state: present

- name: remove cvuqdisk locally
  file:
    path: ./cvuqdisk-1.0.10-1.rpm 
    state: absent
  delegate_to: localhost

- name: remove cvuqdisk from tmp
  file:
    path: /tmp/cvuqdisk-1.0.10-1.rpm 
    state: absent

- name: install gridSetup response file
  template:
    src: gridSetup.rsp.tmpl
    dest: "/home/{{ grid_osuser }}/gridSetup.rsp"
    owner: "{{ grid_osuser }}"
    group: "{{ orainventory.osgroup }}"
    mode: 0750
    
- name: install gridSetup step 1
  template:
    src: 01_gridSetup_prereq.sh
    dest: "/home/{{ grid_osuser }}"
    owner: "{{ grid_osuser }}"
    group: "{{ orainventory.osgroup }}"
    mode: 0750

- name: install ssh keys
  include_tasks: deploy-keys.yml

- name: run gridSetup prereq
  command: "/home/{{ grid_osuser }}/01_gridSetup_prereq.sh"
  become_user: "{{ grid_osuser }}"
  when: run_gridSetup_prereq and
        inventory_hostname == groups.all[0]
  register: prereq_stdout

- name: run gridSetup
  command: "/home/{{ grid_osuser }}/02_gridSetup.sh"
  become_user: "{{ grid_osuser }}"
  when: inventory_hostname == groups.all[0]
  register: gridsetup_stdout

- name: run orainstRoot
  command: "{{ orainventory_location }}/orainstRoot.sh"
  when: inventory_hostname == groups.all[0]

- name: run orainstRoot
  command: "{{ grid_oracle_home }}/root.sh"
  when: inventory_hostname == groups.all[0]

- name: run orainstRoot
  command: "{{ orainventory_location }}/orainstRoot.sh"
  when: inventory_hostname != groups.all[0]

- name: run orainstRoot
  command: "{{ grid_oracle_home }}/root.sh"
  when: inventory_hostname != groups.all[0]

- name: configTools
  command: "{{ grid_oracle_home }}/gridSetup.sh -executeConfigTools -responseFile /home/{{ grid_osuser }}/gridSetup.rsp -silent"
  become_user: "{{ grid_osuser }}"
  when: inventory_hostname == groups.all[0]
