version: '3'

networks:
  default:
    external:
      name: phoenix_network

services:

  #PGPOOL
  pgpool01:
    image: pgpool:9.6.2
    environment:
      PG_MASTER_NODE_NAME: pg01
      PG_BACKEND_NODE_LIST: ${PG_BACKEND_NODE_LIST}
      PGP_NODE_NAME: pgpool01
      REPMGRPWD: ${REPMGRPDW:-evs123}
    ports:
      - 9999:9999
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
