---

  # let us use a group called cluster
  - add_host:
      name: "{{ item }}"
      groups: cluster
    with_items: "{{ groups.phoenix }}"
    when: groups.cluster is undefined

  #- debug: var=groups['cluster']
  - template:
      src: config.j2
      dest: /etc/evs/config
      owner: evs
      group: evs
      mode: 0550
    vars:
      initial_node_type: "{{ (inventory_hostname == groups.cluster[0]) | ternary('master','slave') }}"

  - name: Add IP address of all hosts in /etc/hosts 
    lineinfile:
      dest: /etc/hosts
      line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
      state: present
    with_items: "{{ groups.cluster }}"

  - name: fetch postgres public ssh key
    shell: cat /home/postgres/.ssh/id_rsa.pub
    register: postgres_ssh_keys

  - name: deploy postgres public key to all servers
    authorized_key: user=postgres key="{{ item[0] }}" state=present
    delegate_to: "{{ item[1] }}"
    with_nested:
      - "{{ postgres_ssh_keys.stdout }}"
      - "{{ groups['cluster'] }}"

  - name: generate host key file
    command: "ssh-keyscan -t ecdsa-sha2-nistp256 {{ inventory_hostname }}"
    register: host_pub_key

#  - debug: var=host_pub_key.stdout

  - name: add to know_hosts of other servers
    known_hosts:
      path: /home/postgres/.ssh/known_hosts
      name: "{{ inventory_hostname }}"
      key: "{{ host_pub_key.stdout }}"
    delegate_to: "{{ item }}"
    when: item != inventory_hostname
    with_items:
      - "{{ groups['cluster'] }}"

#  - debug: var=hostvars[item]['ansible_default_ipv4']['address']
#    with_items: "{{ groups['cluster'] }}"

#  - debug: var=groups['cluster'][0]

  - name: determine swarm status on manager node
    shell: >
      docker info | egrep '^Swarm: ' | cut -d ' ' -f2
    register: swarm_manager_status
    when: "inventory_hostname == groups.cluster[0]"

  - debug: var=swarm_manager_status.stdout_lines
    when: inventory_hostname == groups.cluster[0]

  - name: start firewalld
    systemd:
      service: firewalld
      state: started
      enabled: yes

  - name: firewall ports for swarm
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
      immediate: yes
    with_items:
      - 2376/tcp
      - 2377/tcp
      - 7946/tcp
      - 7946/udp
      - 4789/udp

  - name: init swarm
    shell: >
      docker swarm init --advertise-addr "{{ swarm_iface | default(hostvars[groups['cluster'][0]]['ansible_default_ipv4']['address']) }}"
    register: swarm_init
    when: inventory_hostname == groups['cluster'][0] and 'active' not in swarm_manager_status.stdout_lines

  - debug: var=swarm_init.stdout_lines

  - name: retrieve swarm token on manager needed by worker nodes
    shell: >
      docker swarm join-token -q worker
    register: swarm_worker_join_token
    when: inventory_hostname == groups.cluster[0]

  - name: worker nodes join swarm cluster
    shell: >
      docker swarm join --token {{ swarm_worker_join_token.stdout }} {{  swarm_iface | default(hostvars[groups['cluster'][0]]['ansible_default_ipv4']['address']) }}:2377
    ignore_errors: true
    delegate_to: "{{ item }}"
    when: inventory_hostname == groups.cluster[0] and item != groups.cluster[0]
    with_items: 
      - "{{ groups['cluster'] }}"

  - name: docker_swarm | Capturing Docker Swarm Networks
    command: "docker network ls"
    changed_when: false
    register: "docker_networks"
    when: inventory_hostname == groups.cluster[0]

  - debug: var=docker_swarm_networks

  - name: docker_swarm | Creating Docker Swarm Networks
    command: "docker network create --attachable --driver {{ item.value.driver }} {{ item.value.name }}"
    with_dict: "{{ docker_swarm_networks }}"
    when: >
          inventory_hostname == groups.cluster[0] and
          item.value.state|lower == "present" and
          item.value.name not in docker_networks.stdout

  - name: ensure directory /opt/evs/run exists
    file:
      path: /opt/evs/run
      state: directory
      owner: evs
      group: evs
      mode: 0755
  
  - name: install docker-compose.infra.ym in /opt/evs/run
    template: 
      src: "docker-compose.infra.yml"
      dest: "/opt/evs/run/docker-compose.infra.yml"
      owner: evs
      group: evs
      mode: "u=rw,g=r,o=r"

...
