# set-up basic server

---

#  - user:
#      name: evsadmin
#      uid: 1000
#      generate_ssh_key: yes
#      ssh_key_bits: 2048
#      ssh_key_file: .ssh/id_rsa      
#      comment: "admin user, for support"
#      state: present

  - group:
      name: evs
      gid: 2000

  - user:
      name: evs
      uid: 2000
      groups: "wheel,evs"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa      
      comment: "evs user, for running docker containers and EVS applications"
      state: present

  - name: Allow evs user to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^evs'
      line: 'evs ALL=(ALL) NOPASSWD: ALL'

  - name: set hostname to value from inventory
    hostname:
      name: "{{ inventory_hostname }}"

  - name: install epel
    yum:
      name: epel-release
      state: latest

  - name: install python
    yum:
      name: python
      state: latest

  - name: install docker-python
    yum:
      name: docker-python
      state: latest

  - name: upgrade latest
    yum:
      name: "*"
      state: latest

  - name: create directory /opt/evs
    file: path=/opt/evs state=directory owner=evs group=evs mode=0755

  - name: create log directory for evs applications
    file: path=/var/log/evs state=directory owner=evs group=evs mode=0755

  - name: create directory /etc/evs
    file: path=/etc/evs state=directory owner=evs group=evs mode=0750

  - name: install config file
    copy:
      src: config
      dest: /etc/evs/config
      owner: evs
      group: evs
      mode: "u=rw,g=r"

